"""goal_subcategory_link

Revision ID: 39d7cad21ea3
Revises: a7b8c9d0e1f2
Create Date: 2026-06-26 14:51:45.950167
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '39d7cad21ea3'
down_revision: Union[str, None] = 'a7b8c9d0e1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('linked_subcategory_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'goals', 'subcategories', ['linked_subcategory_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.drop_column('goals', 'linked_subcategory_id')
    # ### end Alembic commands ###
