"""user profiles

Revision ID: bf3a609b6bbb
Revises: e40dabfbd86c
Create Date: 2026-07-02 12:17:18.390720
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bf3a609b6bbb'
down_revision: Union[str, None] = 'e40dabfbd86c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('family_size', sa.Integer(), nullable=True),
    sa.Column('dependents', sa.Integer(), nullable=True),
    sa.Column('earners', sa.String(length=10), nullable=True),
    sa.Column('city_tier', sa.String(length=10), nullable=True),
    sa.Column('short_term_goals', sa.String(length=500), nullable=True),
    sa.Column('long_term_goals', sa.String(length=500), nullable=True),
    sa.Column('emergency_fund', sa.String(length=20), nullable=True),
    sa.Column('other_loans', sa.String(length=20), nullable=True),
    sa.Column('savings_level', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
