"""budget revision drafts

Revision ID: e40dabfbd86c
Revises: 4c2f1a8b3e9d
Create Date: 2026-06-29 12:50:52.765259
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e40dabfbd86c'
down_revision: Union[str, None] = '4c2f1a8b3e9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_revision_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('budget_year_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('user_note', sa.Text(), nullable=True),
    sa.Column('insights', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['budget_year_id'], ['budget_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_revision_drafts_budget_year_id'), 'budget_revision_drafts', ['budget_year_id'], unique=False)
    op.create_index(op.f('ix_budget_revision_drafts_user_id'), 'budget_revision_drafts', ['user_id'], unique=False)
    op.create_table('budget_revision_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=False),
    sa.Column('current_annual', sa.Text(), nullable=False),
    sa.Column('revised_annual', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['budget_revision_drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_revision_items_draft_id'), 'budget_revision_items', ['draft_id'], unique=False)
    op.create_index(op.f('ix_budget_revision_items_subcategory_id'), 'budget_revision_items', ['subcategory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budget_revision_items_subcategory_id'), table_name='budget_revision_items')
    op.drop_index(op.f('ix_budget_revision_items_draft_id'), table_name='budget_revision_items')
    op.drop_table('budget_revision_items')
    op.drop_index(op.f('ix_budget_revision_drafts_user_id'), table_name='budget_revision_drafts')
    op.drop_index(op.f('ix_budget_revision_drafts_budget_year_id'), table_name='budget_revision_drafts')
    op.drop_table('budget_revision_drafts')
    # ### end Alembic commands ###
